### ISSUE TITLE
V2 BUG - Single-Option default value is not working

### ISSUE THREAD

**Issue by harrison-peace** [storyblok/storyblok#832]
**The issue occurs while working with:** (check one with "x")   
- [ x] *app.storyblok.com (CMS - Interface)*   

**Current behavior:**
Creating a new Single-Option field and setting a default value in V2 does not work.

**Expected behavior:**
After creating a Single-Option field and setting a default that field should have the default option selected for all instances

**Steps to reproduce:**
Create a new Single-Option field and set a default, add component into content and check if field has default value set or not.

V2
![image](https://user-images.githubusercontent.com/106947080/187820444-b22260d4-4c3f-4f9c-b808-9b7b45ded6e3.png)

V1
![image](https://user-images.githubusercontent.com/106947080/187820518-4423ba2e-ca85-4097-9bd3-bdf9e9d5c602.png)

**Other information:**

**Comment by nachoadjust** [comment]
Same problem here,
This is keeping us from moving into V2, as our Content Managers cannot work and create the stories as they used to.

Things that we noticed that might be triggering the bug:
- the `Use UID instead of ID` disappeared from single-option fields
- the `Exclude from export` disappeared as well (tho this seems to be across all field types)

We have recorded our issue in this video:
https://www.loom.com/share/05d4b53714524847a92b0b4e3b2aef15

Random thought: 
Maybe the intention of Storyblok for V2 is to remove the stories selection from single-options fields 
and funnel it through the link field, but the object models each generate are different and that would imply we need to run a big migration of our data.

**Comment by abrambailey** [comment]
@nachoadjust I have the same problem and produced a video here:

https://photos.google.com/share/AF1QipOn3LyqR041YB92KF86MrWe_KZZoqFBb11PEqoPK9FS3AgAJHOzb-j9omTqgSruPQ/photo/AF1QipNyCUxsvGVAFgDttKXw4PdOtj4ZDS2wZv941Yhi?key=WDlTN0hxTlBfaTk4ZnduTkVqeDJWTTNpQnJhU3F3

**Comment by lisilinhart** [comment]
Thanks @abrambailey. It's better to report bugs through our chat function on the website or app, because then it can be forwarded to the right department. I made some tests here and you are right about it not working. I'll make a hotfix for it now

**Comment by lisilinhart** [comment]
We're already working on getting this live as soon as possible 👍

**Comment by abrambailey** [comment]
Thank you very much !!

**Comment by abrambailey** [comment]
> Thanks @abrambailey. It's better to report bugs through our chat function on the website or app, because then it can be forwarded to the right department. I made some tests here and you are right about it not working. I'll make a hotfix for it now

For the record, I reported in chat twice, even providing the video!

**Comment by lisilinhart** [comment]
@abrambailey @harrison-peace I believe this bug should be solved now

**Comment by abrambailey** [comment]
Hi @lisilinhart when does this become deployed? I tried just now and still seeing the old behavior. Thank you!

**Comment by lisilinhart** [comment]
Hi @abrambailey, it's already deployed, here is a video:


https://user-images.githubusercontent.com/11278408/192333207-06512752-c1c3-41fa-ab6d-e105b10defab.mov

**Comment by abrambailey** [comment]
It's still broken when using external json as a data source.

**Comment by abrambailey** [comment]
Here's my setup:

![image](https://user-images.githubusercontent.com/978462/192347540-afb65769-a28d-40a7-aa53-08c0d6661919.png)

**Comment by lisilinhart** [comment]
Thanks @abrambailey, I'll make some more tests here with the external jsons

**Comment by lisilinhart** [comment]
@abrambailey I see the difference in the behaviour now and we're working on another hotfix. The problem is that in v2 currently the values are validated to Strings and that is an issue, when having number values like in your external json, but we will probably adapt that to work similar to v1. I'll let you know once we found a solution.

**Comment by abrambailey** [comment]
What's weird is that Storyblok supports my external json in multi choice fields. Seems like the string check is only happening on the single select.

**Comment by lisilinhart** [comment]
@abrambailey we already have a hotfix in progress for this to also validate numbers, it's currently in testing. Should be available next week sometime

**Comment by abrambailey** [comment]
Wonderful thanks!
